# Generated by Django 5.2.11 on 2026-02-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MASTER', 'Мастер'), ('MACHINIST', 'Машинист'), ('ASSISTANT', 'Помощник машиниста'), ('MEDIC', 'Медик'), ('INSPECTOR', 'Инспектор/ревизор')], default='MACHINIST', max_length=20, verbose_name='Должность'),
        ),
    ]
