# Generated by Django 5.2.11 on 2026-02-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_patronymic_alter_user_role'),
        ('directory', '0003_machinetype_position_workplace_worktype_brigade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='directory.station', verbose_name='Станция'),
        ),
    ]
