# Generated by Django 5.2.11 on 2026-02-12 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'verbose_name': 'Предприятие', 'verbose_name_plural': 'Предприятия'},
        ),
        migrations.AlterModelOptions(
            name='fueltype',
            options={'verbose_name': 'Топливо', 'verbose_name_plural': 'Топливо'},
        ),
        migrations.AlterModelOptions(
            name='lubricanttype',
            options={'verbose_name': 'Смазка', 'verbose_name_plural': 'Смазочные материалы'},
        ),
        migrations.AlterModelOptions(
            name='sspsunit',
            options={'verbose_name': 'Единица ССПС', 'verbose_name_plural': 'Единицы ССПС'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Станция', 'verbose_name_plural': 'Станции'},
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование предприятия'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Марка топлива'),
        ),
        migrations.AlterField(
            model_name='lubricanttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Марка смазки'),
        ),
        migrations.AlterField(
            model_name='sspsunit',
            name='max_people',
            field=models.PositiveIntegerField(default=0, verbose_name='Макс. число людей'),
        ),
        migrations.AlterField(
            model_name='sspsunit',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Номер ССПС'),
        ),
        migrations.AlterField(
            model_name='sspsunit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.enterprise', verbose_name='Владелец (предприятие)'),
        ),
        migrations.AlterField(
            model_name='sspsunit',
            name='type_name',
            field=models.CharField(max_length=120, verbose_name='Тип ССПС'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Станция'),
        ),
    ]
