# Generated by Django 5.2.11 on 2026-02-13 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_enterprise_options_alter_fueltype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Тип машины (справочник)')),
            ],
            options={
                'verbose_name': 'Тип машины',
                'verbose_name_plural': 'Типы машин',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Должность (справочник)')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Место работ (справочник)')),
            ],
            options={
                'verbose_name': 'Место работ',
                'verbose_name_plural': 'Места работ',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Вид работ (справочник)')),
            ],
            options={
                'verbose_name': 'Вид работ',
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название бригады')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('members', models.ManyToManyField(blank=True, related_name='brigades', to=settings.AUTH_USER_MODEL, verbose_name='Состав бригады (работники)')),
                ('ssps_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brigades', to='directory.sspsunit', verbose_name='Единица ССПС')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
                'unique_together': {('name', 'ssps_unit')},
            },
        ),
    ]
