# Generated by Django 5.2.11 on 2026-02-13 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_machinetype_position_workplace_worktype_brigade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер машины')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='directory.machinetype', verbose_name='Тип машины')),
                ('ssps_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='directory.sspsunit', verbose_name='ССПС')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
                'unique_together': {('machine_type', 'number')},
            },
        ),
    ]
