# Generated by Django 5.2.11 on 2026-02-12 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSheetAU12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('railway_name', models.CharField(blank=True, max_length=255)),
                ('enterprise_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ISSUED', 'Выдан'), ('IN_PROGRESS', 'В работе'), ('CLOSED', 'Закрыт'), ('EXPORTED', 'Экспортирован')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='au12_created', to=settings.AUTH_USER_MODEL)),
                ('ssps_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.sspsunit')),
            ],
        ),
        migrations.CreateModel(
            name='AU12WorkRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(blank=True, max_length=50)),
                ('time_departure', models.TimeField(blank=True, null=True)),
                ('time_arrival', models.TimeField(blank=True, null=True)),
                ('work_name', models.CharField(max_length=255)),
                ('work_place', models.CharField(blank=True, max_length=255)),
                ('machine_work_start', models.TimeField(blank=True, null=True)),
                ('machine_work_end', models.TimeField(blank=True, null=True)),
                ('work_volume', models.CharField(blank=True, max_length=120)),
                ('supervisor_signature', models.CharField(blank=True, max_length=255)),
                ('station_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='directory.station')),
                ('station_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='directory.station')),
                ('routesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_rows', to='routesheets.routesheetau12')),
            ],
        ),
        migrations.CreateModel(
            name='AU12SectionVI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True)),
                ('accepted_by', models.CharField(blank=True, max_length=255)),
                ('routesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_vi', to='routesheets.routesheetau12')),
            ],
        ),
        migrations.CreateModel(
            name='AU12SectionV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinist_admitted_pre', models.BooleanField(default=False)),
                ('assistant_admitted_pre', models.BooleanField(default=False)),
                ('radio_ok', models.BooleanField(default=True)),
                ('ssps_ok', models.BooleanField(default=True)),
                ('safety_device_ok', models.BooleanField(default=True)),
                ('machinist_signature', models.CharField(blank=True, max_length=255)),
                ('responsible_signature', models.CharField(blank=True, max_length=255)),
                ('routesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_v', to='routesheets.routesheetau12')),
            ],
        ),
        migrations.CreateModel(
            name='AU12SectionIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_norm_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fuel_fact_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('lube_norm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('lube_fact', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('routesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_iv', to='routesheets.routesheetau12')),
            ],
        ),
        migrations.CreateModel(
            name='AU12SectionII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_owner_name', models.CharField(blank=True, max_length=255)),
                ('machine_type_name', models.CharField(blank=True, max_length=120)),
                ('machine_number', models.CharField(blank=True, max_length=50)),
                ('speedometer_out_km', models.PositiveIntegerField(blank=True, null=True)),
                ('moto_hours_out', models.PositiveIntegerField(blank=True, null=True)),
                ('speedometer_in_km', models.PositiveIntegerField(blank=True, null=True)),
                ('moto_hours_in', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_issued_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fuel_left_out_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fuel_left_in_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('lubricant_issued', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.fueltype')),
                ('lubricant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.lubricanttype')),
                ('routesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_ii', to='routesheets.routesheetau12')),
            ],
        ),
        migrations.CreateModel(
            name='AU12CrewRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=120)),
                ('full_name', models.CharField(max_length=255)),
                ('time_check_in', models.TimeField(blank=True, null=True)),
                ('time_check_out', models.TimeField(blank=True, null=True)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('rest_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_reason', models.CharField(blank=True, max_length=255)),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('routesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_rows', to='routesheets.routesheetau12')),
            ],
        ),
    ]
