# Generated by Django 5.2.11 on 2026-02-12 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_enterprise_options_alter_fueltype_options_and_more'),
        ('routesheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='au12crewrow',
            options={'verbose_name': 'Строка бригады', 'verbose_name_plural': 'Бригада'},
        ),
        migrations.AlterModelOptions(
            name='au12sectionii',
            options={'verbose_name': 'Раздел II', 'verbose_name_plural': 'Раздел II'},
        ),
        migrations.AlterModelOptions(
            name='au12sectioniv',
            options={'verbose_name': 'Раздел IV', 'verbose_name_plural': 'Раздел IV'},
        ),
        migrations.AlterModelOptions(
            name='au12sectionv',
            options={'verbose_name': 'Раздел V', 'verbose_name_plural': 'Раздел V'},
        ),
        migrations.AlterModelOptions(
            name='au12sectionvi',
            options={'verbose_name': 'Раздел VI', 'verbose_name_plural': 'Раздел VI'},
        ),
        migrations.AlterModelOptions(
            name='au12workrow',
            options={'verbose_name': 'Строка работ', 'verbose_name_plural': 'Работы (раздел III)'},
        ),
        migrations.AlterModelOptions(
            name='routesheetau12',
            options={'verbose_name': 'Маршрутный лист АУ-12', 'verbose_name_plural': 'Маршрутные листы АУ-12'},
        ),
        migrations.AlterField(
            model_name='au12crewrow',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='au12crewrow',
            name='overtime_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Переработка (мин)'),
        ),
        migrations.AlterField(
            model_name='au12crewrow',
            name='overtime_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина переработки'),
        ),
        migrations.AlterField(
            model_name='au12crewrow',
            name='position',
            field=models.CharField(max_length=120, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='au12crewrow',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='au12crewrow',
            name='rest_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Отдых (мин)'),
        ),
        migrations.AlterField(
            model_name='au12crewrow',
            name='routesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_rows', to='routesheets.routesheetau12', verbose_name='Маршрутный лист'),
        ),
        migrations.AlterField(
            model_name='au12crewrow',
            name='time_check_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Явка'),
        ),
        migrations.AlterField(
            model_name='au12crewrow',
            name='time_check_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='enterprise_owner_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предприятие-владелец'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='fuel_issued_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Выдано топлива, л'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='fuel_left_in_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Остаток топлива при возврате, л'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='fuel_left_out_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Остаток топлива при выезде, л'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.fueltype', verbose_name='Марка топлива'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='lubricant_issued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Выдано смазки'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='lubricant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.lubricanttype', verbose_name='Марка смазки'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='machine_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер машины'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='machine_type_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Тип машины'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='moto_hours_in',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Моточасы (возврат)'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='moto_hours_out',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Моточасы (выезд)'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='routesheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_ii', to='routesheets.routesheetau12', verbose_name='Маршрутный лист'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='speedometer_in_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Спидометр (возврат), км'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='speedometer_out_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Спидометр (выезд), км'),
        ),
        migrations.AlterField(
            model_name='au12sectioniv',
            name='fuel_fact_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Факт топлива, л'),
        ),
        migrations.AlterField(
            model_name='au12sectioniv',
            name='fuel_norm_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Норма топлива, л'),
        ),
        migrations.AlterField(
            model_name='au12sectioniv',
            name='lube_fact',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Факт смазки'),
        ),
        migrations.AlterField(
            model_name='au12sectioniv',
            name='lube_norm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Норма смазки'),
        ),
        migrations.AlterField(
            model_name='au12sectioniv',
            name='routesheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_iv', to='routesheets.routesheetau12', verbose_name='Маршрутный лист'),
        ),
        migrations.AlterField(
            model_name='au12sectionv',
            name='assistant_admitted_pre',
            field=models.BooleanField(default=False, verbose_name='Помощник допущен'),
        ),
        migrations.AlterField(
            model_name='au12sectionv',
            name='machinist_admitted_pre',
            field=models.BooleanField(default=False, verbose_name='Машинист допущен'),
        ),
        migrations.AlterField(
            model_name='au12sectionv',
            name='machinist_signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись машиниста'),
        ),
        migrations.AlterField(
            model_name='au12sectionv',
            name='radio_ok',
            field=models.BooleanField(default=True, verbose_name='Радиосвязь исправна'),
        ),
        migrations.AlterField(
            model_name='au12sectionv',
            name='responsible_signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись ответственного'),
        ),
        migrations.AlterField(
            model_name='au12sectionv',
            name='routesheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_v', to='routesheets.routesheetau12', verbose_name='Маршрутный лист'),
        ),
        migrations.AlterField(
            model_name='au12sectionv',
            name='safety_device_ok',
            field=models.BooleanField(default=True, verbose_name='Устройство безопасности исправно'),
        ),
        migrations.AlterField(
            model_name='au12sectionv',
            name='ssps_ok',
            field=models.BooleanField(default=True, verbose_name='Единица ССПС исправна'),
        ),
        migrations.AlterField(
            model_name='au12sectionvi',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Принял'),
        ),
        migrations.AlterField(
            model_name='au12sectionvi',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Замечания'),
        ),
        migrations.AlterField(
            model_name='au12sectionvi',
            name='routesheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_vi', to='routesheets.routesheetau12', verbose_name='Маршрутный лист'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='machine_work_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Окончание работы машины'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='machine_work_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало работы машины'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='request_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='№ заявки'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='routesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_rows', to='routesheets.routesheetau12', verbose_name='Маршрутный лист'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='station_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='directory.station', verbose_name='Станция отправления'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='station_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='directory.station', verbose_name='Станция назначения'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='supervisor_signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись руководителя'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='time_arrival',
            field=models.TimeField(blank=True, null=True, verbose_name='Прибытие'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='time_departure',
            field=models.TimeField(blank=True, null=True, verbose_name='Отправление'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='work_name',
            field=models.CharField(max_length=255, verbose_name='Наименование работ'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='work_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место работ'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='work_volume',
            field=models.CharField(blank=True, max_length=120, verbose_name='Объём работ'),
        ),
        migrations.AlterField(
            model_name='routesheetau12',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='routesheetau12',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='au12_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='routesheetau12',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='routesheetau12',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='routesheetau12',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='routesheetau12',
            name='railway_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование дороги'),
        ),
        migrations.AlterField(
            model_name='routesheetau12',
            name='ssps_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.sspsunit', verbose_name='Единица ССПС'),
        ),
        migrations.AlterField(
            model_name='routesheetau12',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ISSUED', 'Выдан'), ('IN_PROGRESS', 'В работе'), ('CLOSED', 'Закрыт'), ('EXPORTED', 'Экспортирован')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
    ]
