# Generated by Django 5.2.11 on 2026-02-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_machinetype_position_workplace_worktype_brigade'),
        ('routesheets', '0002_alter_au12crewrow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='au12crewrow',
            options={'verbose_name': 'Строка бригады', 'verbose_name_plural': 'Бригада (строки)'},
        ),
        migrations.AlterModelOptions(
            name='routesheetau12',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Маршрутный лист АУ-12', 'verbose_name_plural': 'Маршрутные листы АУ-12'},
        ),
        migrations.RemoveField(
            model_name='au12crewrow',
            name='position',
        ),
        migrations.RemoveField(
            model_name='au12sectioniv',
            name='fuel_fact_l',
        ),
        migrations.RemoveField(
            model_name='au12sectioniv',
            name='fuel_norm_l',
        ),
        migrations.RemoveField(
            model_name='au12sectioniv',
            name='lube_fact',
        ),
        migrations.RemoveField(
            model_name='au12sectioniv',
            name='lube_norm',
        ),
        migrations.RemoveField(
            model_name='au12sectionv',
            name='assistant_admitted_pre',
        ),
        migrations.RemoveField(
            model_name='au12sectionv',
            name='machinist_admitted_pre',
        ),
        migrations.RemoveField(
            model_name='au12sectionv',
            name='machinist_signature',
        ),
        migrations.RemoveField(
            model_name='au12sectionv',
            name='radio_ok',
        ),
        migrations.RemoveField(
            model_name='au12sectionv',
            name='responsible_signature',
        ),
        migrations.RemoveField(
            model_name='au12sectionv',
            name='safety_device_ok',
        ),
        migrations.RemoveField(
            model_name='au12sectionv',
            name='ssps_ok',
        ),
        migrations.RemoveField(
            model_name='au12sectionvi',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='au12sectionvi',
            name='remarks',
        ),
        migrations.AddField(
            model_name='au12crewrow',
            name='position_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.position', verbose_name='Должность (из справочника)'),
        ),
        migrations.AddField(
            model_name='au12crewrow',
            name='position_text',
            field=models.CharField(blank=True, max_length=120, verbose_name='Должность (вручную)'),
        ),
        migrations.AddField(
            model_name='au12sectionii',
            name='enterprise_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.enterprise', verbose_name='Предприятие-владелец (из справочника)'),
        ),
        migrations.AddField(
            model_name='au12sectionii',
            name='machine_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.machinetype', verbose_name='Тип машины (из справочника)'),
        ),
        migrations.AddField(
            model_name='au12sectioniv',
            name='defects_found',
            field=models.TextField(blank=True, verbose_name='Выявленные неисправности'),
        ),
        migrations.AddField(
            model_name='au12sectioniv',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Раздел IV заполнен'),
        ),
        migrations.AddField(
            model_name='au12sectioniv',
            name='measures_taken',
            field=models.TextField(blank=True, verbose_name='Принятые меры'),
        ),
        migrations.AddField(
            model_name='au12sectioniv',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ответственный (ФИО)'),
        ),
        migrations.AddField(
            model_name='au12sectioniv',
            name='responsible_signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись ответственного'),
        ),
        migrations.AddField(
            model_name='au12sectioniv',
            name='sign_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время отметки'),
        ),
        migrations.AddField(
            model_name='au12sectioniv',
            name='technical_state',
            field=models.TextField(blank=True, verbose_name='Техническое состояние/замечания (раздел IV)'),
        ),
        migrations.AddField(
            model_name='au12sectionv',
            name='fuel_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по топливу/ТСМ (раздел V)'),
        ),
        migrations.AddField(
            model_name='au12sectionv',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Раздел V заполнен'),
        ),
        migrations.AddField(
            model_name='au12sectionv',
            name='master_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Мастер (ФИО)'),
        ),
        migrations.AddField(
            model_name='au12sectionv',
            name='master_signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись мастера'),
        ),
        migrations.AddField(
            model_name='au12sectionv',
            name='repairs_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по ремонту/обслуживанию'),
        ),
        migrations.AddField(
            model_name='au12sectionv',
            name='sign_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время отметки'),
        ),
        migrations.AddField(
            model_name='au12sectionvi',
            name='final_notes',
            field=models.TextField(blank=True, verbose_name='Итоговые замечания (раздел VI)'),
        ),
        migrations.AddField(
            model_name='au12sectionvi',
            name='inspector_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Проверил (ФИО)'),
        ),
        migrations.AddField(
            model_name='au12sectionvi',
            name='inspector_signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись проверившего'),
        ),
        migrations.AddField(
            model_name='au12sectionvi',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Раздел VI заполнен'),
        ),
        migrations.AddField(
            model_name='au12sectionvi',
            name='sign_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время отметки'),
        ),
        migrations.AddField(
            model_name='au12workrow',
            name='work_place_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.workplace', verbose_name='Место работ (из справочника)'),
        ),
        migrations.AddField(
            model_name='au12workrow',
            name='work_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.worktype', verbose_name='Вид работ (из справочника)'),
        ),
        migrations.AddField(
            model_name='routesheetau12',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routesheets', to='directory.brigade', verbose_name='Бригада'),
        ),
        migrations.AddField(
            model_name='routesheetau12',
            name='step',
            field=models.CharField(choices=[('MED_PRE', 'Медосмотр (до работы)'), ('MASTER_ISSUE', 'Выдача мастером'), ('CREW_WORK', 'Заполнение бригадой'), ('MED_POST', 'Медосмотр (после работы)'), ('FINAL_REVIEW', 'Проверка/закрытие')], default='MED_PRE', max_length=20, verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='enterprise_owner_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предприятие-владелец (вручную)'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='fuel_issued_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Выдано топлива, л'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='fuel_left_in_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Остаток топлива при возврате, л'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='fuel_left_out_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Остаток топлива при выезде, л'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='lubricant_issued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Выдано смазки'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='machine_type_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Тип машины (вручную)'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='work_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование работ (вручную)'),
        ),
        migrations.AlterField(
            model_name='au12workrow',
            name='work_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место работ (вручную)'),
        ),
        migrations.AlterField(
            model_name='routesheetau12',
            name='ssps_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='au12_routesheets', to='directory.sspsunit', verbose_name='Единица ССПС'),
        ),
        migrations.AlterField(
            model_name='routesheetau12',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ISSUED', 'Выдан'), ('IN_PROGRESS', 'В работе'), ('READY', 'Готов'), ('COMPLETED', 'Выполнен')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='AU12MedicalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_time', models.TimeField(blank=True, null=True, verbose_name='Время медосмотра (до)')),
                ('pre_allowed', models.BooleanField(default=False, verbose_name='Допущен (до)')),
                ('pre_medic_name', models.CharField(blank=True, max_length=255, verbose_name='Медик (до)')),
                ('post_time', models.TimeField(blank=True, null=True, verbose_name='Время медосмотра (после)')),
                ('post_allowed', models.BooleanField(default=False, verbose_name='Допущен (после)')),
                ('post_medic_name', models.CharField(blank=True, max_length=255, verbose_name='Медик (после)')),
                ('routesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='routesheets.routesheetau12', verbose_name='Маршрутный лист')),
            ],
            options={
                'verbose_name': 'Медосмотр',
                'verbose_name_plural': 'Медосмотры',
            },
        ),
    ]
