# Generated by Django 5.2.11 on 2026-02-13 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_transportunit'),
        ('routesheets', '0003_alter_au12crewrow_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='au12sectionii',
            name='enterprise_owner',
        ),
        migrations.RemoveField(
            model_name='au12sectionii',
            name='enterprise_owner_name',
        ),
        migrations.RemoveField(
            model_name='au12sectionii',
            name='machine_number',
        ),
        migrations.RemoveField(
            model_name='au12sectionii',
            name='machine_type_name',
        ),
        migrations.RemoveField(
            model_name='au12sectionii',
            name='machine_type_ref',
        ),
        migrations.AddField(
            model_name='au12sectionii',
            name='machine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.machinetype', verbose_name='Тип машины'),
        ),
        migrations.AddField(
            model_name='au12sectionii',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.transportunit', verbose_name='Номер машины'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='moto_hours_in',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Моточасы (возврат)'),
        ),
        migrations.AlterField(
            model_name='au12sectionii',
            name='moto_hours_out',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Моточасы (выезд)'),
        ),
    ]
