# Generated by Django 5.2.11 on 2026-02-14 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_transportunit'),
        ('routesheets', '0004_remove_au12sectionii_enterprise_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routesheetau12',
            name='enterprise_name',
        ),
        migrations.AddField(
            model_name='routesheetau12',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routesheets', to='directory.enterprise', verbose_name='Предприятие'),
        ),
    ]
